spring:
  profiles:
    active: dev

#公共配置与profiles选择无关 mapperLocations指的路径是src/main/resources
mybatis:
  typeAliasesPackage: com.yunlsp.saas.service.bean
  mapperLocations: classpath:mapper/*.xml

---
# 测试环境配置
spring:
  profiles: dev

  datasource:
    url: jdbc:mysql://sh-cdb-pwfw754d.sql.tencentcdb.com:63901/saas?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true&useSSL=false
    username: test
    password: 1qaz@WSX3edc
    driver-class-name: com.mysql.jdbc.Driver
    # 使用druid数据源
    type: com.alibaba.druid.pool.DruidDataSource
    validationQuery: select 'x'

dubbo:
  application:
    name: yunlsp-saas-service-server-test
  registry:
    address: nacos://192.168.2.75:8848

nacos:
  config:
    # namespace: f1dbf3c7-940b-4da5-8f75-d4ae89802d74
    server-addr: 192.168.2.75:8848
    enabled: true

---
# 正式环境配置
spring:
  profiles: online

  datasource:
    url: jdbc:mysql://sh-cdb-pwfw754d.sql.tencentcdb.com:63901/saas?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true&useSSL=false
    username: test
    password: 1qaz@WSX3edc
    driver-class-name: com.mysql.jdbc.Driver
    # 使用druid数据源
    type: com.alibaba.druid.pool.DruidDataSource
    maxActive: 20
    initialSize: 1
    maxWait: 60000
    minIdle: 1
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: select 'x'
    poolPreparedStatements: true
    maxOpenPreparedStatements: 20

# dubbo配置信息
dubbo:
  application:
    name: yunlsp-saas-service-server-test
  registry:
    address: nacos://192.168.2.75:8848

# nacos配置信息
nacos:
  config:
    # namespace: dbf7a8f1-c0a0-4b3f-b5e1-e714a1419a31
    server-addr: 192.168.2.75:8848
    enabled: true


